[package]
name = "tracing-gstreamer"
version = "0.2.2"
edition = "2018"
authors = ["Simonas Kazlauskas <tracing-gstreamer@kazlauskas.me>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/standard-ai/tracing-gstreamer"
documentation = "https://docs.rs/tracing-gstreamer/"
readme = "README.mkd"
description = "Bridge between gstreamer and the tracing ecosystem"
keywords = ["tracing", "logging", "gstreamer", "multimedia"]
categories = ["development-tools::debugging", "development-tools::profiling"]

[lib]
harness = false
crate-type = ["cdylib", "rlib"]

[dependencies]
libc = "0.2.69"
once_cell = "1.8"
tracing = "0.1"
tracing-core = ">=0.1.17, <=0.1.21"
gstreamer = "0.17.3"
thread_local = "1"

[dev-dependencies]
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-tracy = "0.7"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "tracing_gstreamer_docs"]
